import Opcode from "./Opcode.js";
import OperandKind from "./OperandKind.js";

const OPERAND_KINDS_BY_OPCODE = new Map([
    [Opcode.NOP, []],
    [Opcode.THROW, []],
    [Opcode.GETSUPER, [OperandKind.U30_MULTINAME_INDEX]],
    [Opcode.SETSUPER, [OperandKind.U30_MULTINAME_INDEX]],
    [Opcode.DXNS, [OperandKind.U30_STRING_INDEX]],
    [Opcode.DXNSLATE, []],
    [Opcode.KILL, [OperandKind.U30_REGISTER_INDEX]],
    [Opcode.LABEL, []],
    [Opcode.IFNLT, [OperandKind.S24_BRANCH_OFFSET]],
    [Opcode.IFNLE, [OperandKind.S24_BRANCH_OFFSET]],
    [Opcode.IFNGT, [OperandKind.S24_BRANCH_OFFSET]],
    [Opcode.IFNGE, [OperandKind.S24_BRANCH_OFFSET]],
    [Opcode.JUMP, [OperandKind.S24_BRANCH_OFFSET]],
    [Opcode.IFTRUE, [OperandKind.S24_BRANCH_OFFSET]],
    [Opcode.IFFALSE, [OperandKind.S24_BRANCH_OFFSET]],
    [Opcode.IFEQ, [OperandKind.S24_BRANCH_OFFSET]],
    [Opcode.IFNE, [OperandKind.S24_BRANCH_OFFSET]],
    [Opcode.IFLT, [OperandKind.S24_BRANCH_OFFSET]],
    [Opcode.IFLE, [OperandKind.S24_BRANCH_OFFSET]],
    [Opcode.IFGT, [OperandKind.S24_BRANCH_OFFSET]],
    [Opcode.IFGE, [OperandKind.S24_BRANCH_OFFSET]],
    [Opcode.IFSTRICTEQ, [OperandKind.S24_BRANCH_OFFSET]],
    [Opcode.IFSTRICTNE, [OperandKind.S24_BRANCH_OFFSET]],
    // LOOKUPSWITCH is deliberately absent: its operand count depends on a
    // case_count it carries, so CodeReader decodes it with bespoke logic
    // instead of a static shape (see CodeReader.#readLookupSwitchOperands).
    [Opcode.PUSHWITH, []],
    [Opcode.POPSCOPE, []],
    [Opcode.NEXTNAME, []],
    [Opcode.HASNEXT, []],
    [Opcode.PUSHNULL, []],
    [Opcode.PUSHUNDEFINED, []],
    [Opcode.NEXTVALUE, []],
    [Opcode.PUSHBYTE, [OperandKind.S8_BYTE_VALUE]],
    [Opcode.PUSHSHORT, [OperandKind.S32_RAW_VALUE]],
    [Opcode.PUSHTRUE, []],
    [Opcode.PUSHFALSE, []],
    [Opcode.PUSHNAN, []],
    [Opcode.POP, []],
    [Opcode.DUP, []],
    [Opcode.SWAP, []],
    [Opcode.PUSHSTRING, [OperandKind.U30_STRING_INDEX]],
    [Opcode.PUSHINT, [OperandKind.U30_INT_INDEX]],
    [Opcode.PUSHUINT, [OperandKind.U30_UINT_INDEX]],
    [Opcode.PUSHDOUBLE, [OperandKind.U30_DOUBLE_INDEX]],
    [Opcode.PUSHSCOPE, []],
    [Opcode.PUSHNAMESPACE, [OperandKind.U30_NAMESPACE_INDEX]],
    [Opcode.HASNEXT2, [OperandKind.U30_REGISTER_INDEX, OperandKind.U30_REGISTER_INDEX]],
    [Opcode.NEWFUNCTION, [OperandKind.U30_METHOD_INDEX]],
    [Opcode.CALL, [OperandKind.U30_ARG_COUNT]],
    [Opcode.CONSTRUCT, [OperandKind.U30_ARG_COUNT]],
    [Opcode.CALLMETHOD, [OperandKind.U30_DISP_ID, OperandKind.U30_ARG_COUNT]],
    [Opcode.CALLSTATIC, [OperandKind.U30_METHOD_INDEX, OperandKind.U30_ARG_COUNT]],
    [Opcode.CALLSUPER, [OperandKind.U30_MULTINAME_INDEX, OperandKind.U30_ARG_COUNT]],
    [Opcode.CALLPROPERTY, [OperandKind.U30_MULTINAME_INDEX, OperandKind.U30_ARG_COUNT]],
    [Opcode.RETURNVOID, []],
    [Opcode.RETURNVALUE, []],
    [Opcode.CONSTRUCTSUPER, [OperandKind.U30_ARG_COUNT]],
    [Opcode.CONSTRUCTPROP, [OperandKind.U30_MULTINAME_INDEX, OperandKind.U30_ARG_COUNT]],
    [Opcode.CALLPROPLEX, [OperandKind.U30_MULTINAME_INDEX, OperandKind.U30_ARG_COUNT]],
    [Opcode.CALLSUPERVOID, [OperandKind.U30_MULTINAME_INDEX, OperandKind.U30_ARG_COUNT]],
    [Opcode.CALLPROPVOID, [OperandKind.U30_MULTINAME_INDEX, OperandKind.U30_ARG_COUNT]],
    [Opcode.CONSTRUCTGENERICTYPE, [OperandKind.U30_ARG_COUNT]],
    [Opcode.NEWOBJECT, [OperandKind.U30_ARG_COUNT]],
    [Opcode.NEWARRAY, [OperandKind.U30_ARG_COUNT]],
    [Opcode.NEWACTIVATION, []],
    [Opcode.NEWCLASS, [OperandKind.U30_CLASS_INDEX]],
    [Opcode.GETDESCENDANTS, [OperandKind.U30_MULTINAME_INDEX]],
    [Opcode.NEWCATCH, [OperandKind.U30_EXCEPTION_INDEX]],
    [Opcode.FINDPROPSTRICT, [OperandKind.U30_MULTINAME_INDEX]],
    [Opcode.FINDPROPERTY, [OperandKind.U30_MULTINAME_INDEX]],
    [Opcode.GETLEX, [OperandKind.U30_MULTINAME_INDEX]],
    [Opcode.SETPROPERTY, [OperandKind.U30_MULTINAME_INDEX]],
    [Opcode.GETLOCAL, [OperandKind.U30_REGISTER_INDEX]],
    [Opcode.SETLOCAL, [OperandKind.U30_REGISTER_INDEX]],
    [Opcode.GETGLOBALSCOPE, []],
    [Opcode.GETSCOPEOBJECT, [OperandKind.U8_SCOPE_INDEX]],
    [Opcode.GETPROPERTY, [OperandKind.U30_MULTINAME_INDEX]],
    [Opcode.INITPROPERTY, [OperandKind.U30_MULTINAME_INDEX]],
    [Opcode.DELETEPROPERTY, [OperandKind.U30_MULTINAME_INDEX]],
    [Opcode.GETSLOT, [OperandKind.U30_SLOT_INDEX]],
    [Opcode.SETSLOT, [OperandKind.U30_SLOT_INDEX]],
    [Opcode.GETGLOBALSLOT, [OperandKind.U30_SLOT_INDEX]],
    [Opcode.SETGLOBALSLOT, [OperandKind.U30_SLOT_INDEX]],
    [Opcode.CONVERT_S, []],
    [Opcode.ESC_XELEM, []],
    [Opcode.ESC_XATTR, []],
    [Opcode.CONVERT_I, []],
    [Opcode.CONVERT_U, []],
    [Opcode.CONVERT_D, []],
    [Opcode.CONVERT_B, []],
    [Opcode.CONVERT_O, []],
    [Opcode.CHECKFILTER, []],
    [Opcode.COERCE, [OperandKind.U30_MULTINAME_INDEX]],
    [Opcode.COERCE_A, []],
    [Opcode.COERCE_S, []],
    [Opcode.ASTYPE, [OperandKind.U30_MULTINAME_INDEX]],
    [Opcode.ASTYPELATE, []],
    [Opcode.NEGATE, []],
    [Opcode.INCREMENT, []],
    [Opcode.INCLOCAL, [OperandKind.U30_REGISTER_INDEX]],
    [Opcode.DECREMENT, []],
    [Opcode.DECLOCAL, [OperandKind.U30_REGISTER_INDEX]],
    [Opcode.TYPEOF, []],
    [Opcode.NOT, []],
    [Opcode.BITNOT, []],
    [Opcode.ADD, []],
    [Opcode.SUBTRACT, []],
    [Opcode.MULTIPLY, []],
    [Opcode.DIVIDE, []],
    [Opcode.MODULO, []],
    [Opcode.LSHIFT, []],
    [Opcode.RSHIFT, []],
    [Opcode.URSHIFT, []],
    [Opcode.BITAND, []],
    [Opcode.BITOR, []],
    [Opcode.BITXOR, []],
    [Opcode.EQUALS, []],
    [Opcode.STRICTEQUALS, []],
    [Opcode.LESSTHAN, []],
    [Opcode.LESSEQUALS, []],
    [Opcode.GREATERTHAN, []],
    [Opcode.GREATEREQUALS, []],
    [Opcode.INSTANCEOF, []],
    [Opcode.ISTYPE, [OperandKind.U30_MULTINAME_INDEX]],
    [Opcode.ISTYPELATE, []],
    [Opcode.IN, []],
    [Opcode.INCREMENT_I, []],
    [Opcode.DECREMENT_I, []],
    [Opcode.INCLOCAL_I, [OperandKind.U30_REGISTER_INDEX]],
    [Opcode.DECLOCAL_I, [OperandKind.U30_REGISTER_INDEX]],
    [Opcode.NEGATE_I, []],
    [Opcode.ADD_I, []],
    [Opcode.SUBTRACT_I, []],
    [Opcode.MULTIPLY_I, []],
    [Opcode.GETLOCAL0, []],
    [Opcode.GETLOCAL1, []],
    [Opcode.GETLOCAL2, []],
    [Opcode.GETLOCAL3, []],
    [Opcode.SETLOCAL0, []],
    [Opcode.SETLOCAL1, []],
    [Opcode.SETLOCAL2, []],
    [Opcode.SETLOCAL3, []],
    [Opcode.DEBUG, [
        OperandKind.U8_DEBUG_TYPE, OperandKind.U30_STRING_INDEX,
        OperandKind.U8_REGISTER_INDEX, OperandKind.U30_UNUSED
    ]],
    [Opcode.DEBUGLINE, [OperandKind.U30_LINE_NUMBER]],
    [Opcode.DEBUGFILE, [OperandKind.U30_STRING_INDEX]]
]);

// Static operand shape per supported opcode, per AVM2 Overview Chapter 5
// (docs/abc/05-5-avm2-instructions.md). Drives decoding and, later,
// formatting/interpretation.
class InstructionShape {

    static operandKindsFor(opcode) {
        const kinds = OPERAND_KINDS_BY_OPCODE.get(opcode);
        if (!kinds) {
            throw new Error(`InstructionShape: unknown opcode 0x${opcode.toString(16)}`);
        }
        return kinds;
    }
}

export default InstructionShape;
